# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  VersaLib_config = debug
  VersaEditor_config = debug

else ifeq ($(config),release)
  VersaLib_config = release
  VersaEditor_config = release

else ifeq ($(config),dist)
  VersaLib_config = dist
  VersaEditor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := VersaLib VersaEditor

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

VersaLib:
ifneq (,$(VersaLib_config))
	@echo "==== Building VersaLib ($(VersaLib_config)) ===="
	@${MAKE} --no-print-directory -C VersaLib -f Makefile config=$(VersaLib_config)
endif

VersaEditor: VersaLib
ifneq (,$(VersaEditor_config))
	@echo "==== Building VersaEditor ($(VersaEditor_config)) ===="
	@${MAKE} --no-print-directory -C VersaEditor -f Makefile config=$(VersaEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C VersaLib -f Makefile clean
	@${MAKE} --no-print-directory -C VersaEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   VersaLib"
	@echo "   VersaEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"