site_name: VersaMachina
theme:
  name: material

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
    - Home: index.md
    - Getting Started: start.md
    - Tutorials: Tutorials/index.md
    - Glossary: Glossary/index.md
    - API Reference:
      - Audio: API/Audio/index.md
      - Events: API/Events/index.md
      - Graphics:
        - Platform Agnostic:
          - 2D Graphics: API/Graphics/2D/index.md
          - 3D Graphics: API/Graphics/3D/index.md
        - Platform Specific:
          - Frame Buffer: API/Graphics/Renderer/FrameBuffer/index.md
          - Index Buffer: API/Graphics/Renderer/IndexBuffer/index.md
          - Pipelines: API/Graphics/Renderer/Pipelines/index.md
          - Renderer: API/Graphics/Renderer/index.md
          - Render Commands: API/Graphics/Renderer/RenderCommands/index.md
          - Render Context: API/Graphics/Renderer/RenderContext/index.md
          - Render Passes: API/Graphics/Renderer/RenderPasses/index.md
          - Shader: API/Graphics/Renderer/Shader/index.md
          - States: API/Graphics/Renderer/States/index.md
          - Swap Chain: API/Graphics/Renderer/Swap/index.md
          - Texture: API/Graphics/Renderer/Texture/index.md
          - Vertex Buffer: API/Graphics/Renderer/VertexBuffer/index.md
          - Window: API/Graphics/Window/index.md
      - Input: API/Input/index.md
      - Logging: API/Logging/index.md
      - Networking: API/Networking/index.md
      - Physics: API/Physics/index.md
      - Robotics: API/Robotics/index.md
      - Scripting: API/Scripting/index.md
      - Sensors: API/Sensor/index.md
      - Serialization: API/Serialization/index.md
    - Releases: Release/index.md
    - References: References/index.md
    - Troubleshooting: Troubleshooting/index.md

docs_dir: docs